server:
  port: 8090
eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: localhost
    #表示将自己IP注册到服务中心
    prefer-ip-address: true
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: true
    #由于自己就是客户端，需要向服务器注册信息
    fetch-registry: true
    #设置向服务中心发起心跳的时间（s）
    registry-fetch-interval-seconds: 50
    service-url:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://samphin:samphin123@localhost:8787/eureka/
spring:
  application:
    name: microservice-elasticsearch

elasticsearch:
  host: 127.0.0.1
  port: 9200
  username: elastic
  password: changme
  schema: http
  connectNum: 10
  connectPerRoute: 30