server:
  #服务注册中心端口号
  port: 8789
eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: localhost
    #表示将自己IP注册到服务中心
    prefer-ip-address: true
    #自定义元数据,key/value都可以随便写
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: true
    #由于自己就是客户端，需要向服务器注册信息
    fetch-registry: true
    #设置向服务中心发起心跳的时间（s）
    registry-fetch-interval-seconds: 50
    service-url:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://samphin:samphin123@localhost:8787/eureka/
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: HystrixSystemMQ
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/archives?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: root
logging:
  level:
    org.springframework.web: debug
    root: warn