server:
  #服务注册中心端口号
  port: 8789
eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: localhost
    #表示将自己IP注册到服务中心
    prefer-ip-address: true
    #自定义元数据,key/value都可以随便写
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: true
    #由于自己就是客户端，需要向服务器注册信息
    fetch-registry: true
    #设置向服务中心发起心跳的时间（s）
    registry-fetch-interval-seconds: 50
    service-url:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://samphin:samphin123@localhost:8787/eureka/
spring:
  application:
    name: microservice-archive-feign
  #该参数用来开启重试机制
  cloud:
    loadbalancer:
      retry:
        enabled: true
ribbon:
  eureka:
    enabled: true
  http:
    client:
      enabled: true
#用户微服务配置
MICROSERVICE-USER:
  ribbon:
    # 请求连接超时时间
    ConnectTimeout: 500
    # 请求处理的超时时间
    ReadTimeout: 2000
    # 切换实例的重试次数
    OkToRetryOnAllOperations: true
    # 对当前实例重试次数
    MaxAutoRetriesNextServer: 2
logging:
  level:
    org.springframework.web: debug
    root: warn