server:
  #服务注册中心端口号
  port: 8789
eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: localhost
    #表示将自己IP注册到服务中心
    prefer-ip-address: true
    #自定义元数据,key/value都可以随便写
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: true
    #由于自己就是客户端，需要向服务器注册信息
    fetch-registry: true
    #设置向服务中心发起心跳的时间（s）
    registry-fetch-interval-seconds: 50
    service-url:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://samphin:samphin123@localhost:8787/eureka/
spring:
  application:
    name: microservice-archive-feign
  #该参数用来开启重试机制
  cloud:
    loadbalancer:
      retry:
        enabled: true # 开启Spring Cloud的重试功能
feign:
  hystrix:
    enabled: true # 启用消费方熔断机制
  compression:
    request:
      enabled: true
      mime-types: # 可压缩类型
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048 #内容超过2048字节就进行压缩
#请求用户服务配置负载均衡配置：
microservice-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #规则:随机________默认:轮循
    ConnectTimeout: 250 # Ribbon的连接超时时间
    ReadTimeout: 1000 # Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
    MaxAutoRetries: 1 # 对当前实例的重试次数
ribbon:
  eureka:
    enabled: true
  http:
    client:
      enabled: true
logging:
  level:
    org.springframework.web: debug
    root: warn

management:
    endpoints:
      web:
        exposure:
          exclude: '*'
    endpoint:
      health:
        show-details: always