server:
  #服务注册中心端口号
  port: 8787
eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: 127.0.0.1
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: false
    #由于自己就是服务器，不需要注册到自己
    fetch-registry: false
    service-url:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: microservice-server

logging:
  level:
    org.springframework.web: debug
    com.netflix:
      eureka: off
      discovery: off
    root: warn