server:
  #服务注册中心端口号
  port: 8790

logging:
  level:
    org.springframework.web: debug
    root: warn

#不集成eureka单独使用ribbon也能达到客户端负载均衡作用
ribbon:
  eureka:
    enabled: false

#针对具体服务设置策略
microservice-user:
  ribbon:
    listOfServers: http://localhost:8001,http://localhost:8002,http://localhost:8003