server:
  #服务注册中心端口号
  port: 12700
spring:
  application:
    name: microservice-mongo
  rabbitmq:
    host: 192.168.199.98
    port: 5672
    username: mqadmin
    password: mqadmin
  redis:
    # Redis数据库索引(默认为0)
    database: 0
    # Redis服务器地址
    host: 192.168.199.98
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码(默认为空，我现在设置了密码为foobared)
    password: foobared
    # Redis连接超时时间（毫秒）
    timeout: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  data:
    mongodb:
      #以安全认证模式连接
      uri: mongodb://samphin:samphin@192.168.199.98:27022/test
      host: 192.168.199.98
      port: 27022
      database: test
      username: samphin
      password: samphin
# slf4j日志配置
logging:
  # 配置级别
  level:
    root: warn
    #分包配置级别，即不同的目录下可以使用不同的级别
    org.common.eureka: error
    org.springframework.web: debug
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG #配置MongoTemplate日志
  # 在不指定路径，只指定输出日志的文件名，默认输出至当前项目下
  # 若指定，则会输出至指定目录下
  file: D:/logs/microservice-mongo.log
