server:
  #服务注册中心端口号
  port: 8003
eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: localhost
    #表示将自己IP注册到服务中心
    prefer-ip-address: true
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: true
    #由于自己就是客户端，需要向服务器注册信息
    fetch-registry: true
    #设置向服务中心发起心跳的时间（s）
    registry-fetch-interval-seconds: 50
    service-url:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://samphin:samphin123@localhost:8787/eureka/
spring:
  application:
    name: microservice-user
  #添加微服务链路跟踪
  zipkin:
    base-url: http://localhost:8099/
  sleuth:
    sampler:
      percentage: 1.0
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    #microservice是自定义数据库名称，可以改，其他保持不变，5.7默认采用SSL配置，如果没有配置，就将useSSL=false
    url: jdbc:mysql://192.168.199.98:3306/microservice?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    continueOnError: false   #有了错误是否继续运行
  jpa:
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
        #控制台打印SQL
        hibernate.show_sql: true
        #格式化sql语句
        hibernate.format_sql: true
        #指出是什么操作生成了该语句
        hibernate.use_sql_comments: true
        #根据表动态生成表结构
        hibernate.ddl-auto: update
      
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG