server:
  #服务注册中心端口号
  port: 8056
eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: localhost
    #表示将自己IP注册到服务中心
    prefer-ip-address: false
    #自定义元数据,key/value都可以随便写
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: false
    #由于自己就是客户端，需要向服务器注册信息
    fetch-registry: false
    #设置向服务中心发起心跳的时间（s）
    registry-fetch-interval-seconds: 50
    service-url:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://samphin:samphin123@localhost:8787/eureka/
spring:
  application:
    name: microservice-rabbit-archive
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    #archives是自定义数据库名称，可以改，其他保持不变，5.7默认采用SSL配置，如果没有配置，就将useSSL=false
    url: jdbc:mysql://localhost:3306/microservice?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    initialize: false         #是否初始化数据库
    continueOnError: false   #有了错误是否继续运行
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #生产端
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
logging:
  level:
    org.springframework.web: debug
    root: warn